### ISSUE TITLE
SSL handshake failed on verifying the certificate

### ISSUE THREAD

**Issue by unixb0y** [Fatal1ty/aioapns#20]
Hello,
I'm basically running your "usage example" script (and have been doing for lots of months), but it started throwing the aforementioned error.
I'm not entirely sure, when it started doing it, might be days or weeks.

This is the message and it repeats forever:
```
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x75c68db0>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
SSL error in data received
```

I tried running the code on my Mac, which gave 0 issues, but on the RaspberryPi it does. Maybe the Mac trusts some Apple servers that the Pi doesn't? Or some certificate on the Pi expired? I'm not sure how to update certs on the Pi, already tried system update / upgrade but without luck.

**Comment by reivilibre** [comment]
@unixb0y 

On Debian, the required certificate for APNs was removed from the system
store at some point (not sure if it ever got readded or otherwise
solved), if I recall. Your Pi is probably running a Debian distribution?

Take a look at https://github.com/matrix-org/sygnal/pull/141/files for
how we resolved it on our Docker image, which is based on Debian — we
downloaded the required GeoTrust_Global_CA.crt certificate from https://www.geotrust.com/resources/root-certificates/ and added it
to the system's certificate store (updating with `update-ca-certificates`)...

*(In general, you shouldn't trust strangers on the internet to tell you what certificates to install to your trust store...)*

Also see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596

Hope this helps.

**Comment by unixb0y** [comment]
Thanks a lot, wasn't aware of this Debian bug and the interwebs didn't help me too much via search engine somehow!
I know I shouldn't trust anyone, so I verified the certificate myself though, installed it and everything's back in order, thank you!
