### ISSUE TITLE
Connections terminate with a reason of `Shutdown`

### ISSUE THREAD

**Issue by PeqNP** [Fatal1ty/aioapns#63]
I have a service that uses this library. After a few hours I start getting the following message for all notifications:

```
2024-03-20 10:30:31.906 WARNING connection:on_connection_terminated:295 - Connection <aioapns.connection.APNsProductionClientProtocol object at 0x7fe3540def10> terminated: code=ErrorCodes.NO_ERROR, additional_data=b'{"reason":"Shutdown"}', last_stream_id=1
```

Restarting the service resolves the issue.

My process is as follows:

Create client
```
def get_apn_client(...):
   # ... code here
    return APNs(
        key=cfg.apn_key,
        key_id=cfg.apn_key_id,
        team_id=cfg.apn_team_id,
        topic=cfg.apn_topic,  # Bundle ID
        use_sandbox=use_sandbox
    )
```

Create event loop and send message to a specific user's devices
```
        loop = asyncio.get_event_loop()
        loop.run_until_complete(send_messages(self.client, devices, msg, context, origination))
```

Iterate over every device and send a notification
```
def send_messages(...):
    # ... code here

    for device in devices:
        request = NotificationRequest(
            device_token=device.deviceToken,
            message=message,
            notification_id=str(uuid4()),  # optional
            time_to_live=3,                # optional
            push_type=PushType.ALERT,      # optional
        )
        await client.send_notification(request)
```

This is not efficient at all, I understand. I shoehorned this into a non asyncio model. That will be fixed.

Regardless, I'm creating a new client every time I send new messages. Perhaps I have to cache the `APNs` client because of the connection pool? I see that the code automatically refreshes the token based on a TTL. Theoretically I can use the same client for all sends and it will automatically update the JWT as needed.

**Comment by Fatal1ty** [comment]
Hi @PeqNP 

> Regardless, I'm creating a new client every time I send new messages. Perhaps I have to cache the APNs client because of the connection pool? I see that the code automatically refreshes the token based on a TTL. Theoretically I can use the same client for all sends and it will automatically update the JWT as needed.

Using one client is how this library is supposed to be used. The internal connection pool is doing its job. And indeed, you won't get performance benefits from creating a new client every time.

As for the error, it's hard to say. Judging by `b'{"reason":"Shutdown"}'`, the server on the other side probably says it's shutting down because, well, it happens. This is what a connection pool is for — if the server closes the connection, the pool will free up the resource and create a new connection if necessary. APNS server here implements a graceful shutdown so that the client stops sending anything.

In the worst case, when you send a notification under high load while closing the connection, you will see the warning:
https://github.com/Fatal1ty/aioapns/blob/be9a827babb170de993484d8aa0a4bb9ba59cc0c/aioapns/connection.py#L417-L421
But in any case, the client will try to resend your notification automatically until the number of attempts reaches the maximum.

**Comment by PeqNP** [comment]
Yes. I think it's working just fine and your explanation makes sense.

I have since changed it to create the client only once. I still get the `Shutdown` "error," but the messages are going through just fine. Thank you so much!
